# Generated by Django 4.2.7 on 2024-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
