# Generated by Django 4.2.7 on 2024-03-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_products_image_products_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Изображение'),
        ),
    ]
